### PR TITLE
Fix nginx and openjdk installation

### PR DESCRIPTION
**Pull request by adrian-evo**
When installing nginx and openjdk with generate_box.sh, nginx and openjdk-o-jdk cannot be installed without using --force-yes option

### CODE REVIEW

**Comment by mcjaeger** [comment]
awww, did not see it so far, sorry, will have a look

**Comment by alexbrdn** [comment]
I wonder why the there are so many diff lines. Can it be that you committed with Windows line endings, @adrian-evo?

**Comment by adrian-evo** [comment]
True. Fixed EOL of the commited file.

**Comment by maierthomas** [comment]
@adrian-evo @mcjaeger @alexbrdn push!
This is also relevant for the vagrant aws deployment because openjdk is not available on Ubuntu 16.04 AMI.

**Comment by maierthomas** [comment]
will be resolved in #16

**Pull request closed without merging**
