### PR TITLE
new version ubuntu 20.04, couchdb 3.1.1 and liferay 7.3.4

### PR DESCRIPTION
**Pull request by mcjaeger**
After some unsuccessful tests with liferay 7.3.5, here a new setup which has been tested successfully:

* Ubuntu latest LTS 20.04 focal fossa (implies new version of postresgl, needs new puppet module)
* Couchdb 3.1.1 (latest at the time of writing) installed form the couchdb-apache ppa, needs setting of admin account at installation, see below
* Liferay portal 7.3.4 GA5, unfortunately installing Liferay portal 7.3.5 GA6 failed, because the lar files are not compatible (and I was too lazy to create new ones)

-> tested with SPDX BOM import, SPDX license impoart and readme generation -> works nicely. Files used:

[SPDX2_time-1.9.tar.gz_1535120734-spdx.rdf.zip](https://github.com/sw360/sw360vagrant/files/6058100/SPDX2_time-1.9.tar.gz_1535120734-spdx.rdf.zip)
[SPDX2_zlib128.zip_example-spdx 2.rdf.zip](https://github.com/sw360/sw360vagrant/files/6058101/SPDX2_zlib128.zip_example-spdx.2.rdf.zip)
[bom.spdx.rdf.zip](https://github.com/sw360/sw360vagrant/files/6058098/bom.spdx.rdf.zip)

**Known Issue**

It currently does not work out of the box, it fails in fact at tests for the maven java run. The reason for this is that the couchdb will work only with a password set for the admin account. Therefore the tests need an own `couchdb.properties` file, which is not supported right now. Currently, the `couchdb.properties` would apply for uit tests and deployed version of sw360. A file `couchdb.properties` in `/etc/sw360`, however, is needed to to set the database password.

So, in order to merge this, a modification of the eclipse sw360 is required which allows for separate settings f

**Not Updated**

* still at Java 11
* still couchdb-lucene 2.1
* still spring, thrift and so on ...

**Something Completely Different**

here are the lar files generated from an installation of 7.3.4, maybe they can be useful to be installed to 7.3.5:

[Public_Pages-7_3_4_GA5.lar.zip](https://github.com/sw360/sw360vagrant/files/6058095/Public_Pages-7_3_4_GA5.lar.zip)
[Private_Pages-7_3_4_GA5.lar.zip](https://github.com/sw360/sw360vagrant/files/6058097/Private_Pages-7_3_4_GA5.lar.zip)

### CODE REVIEW

**Comment by mcjaeger** [comment]
updated also couchdb 3 ...

**Comment by mcjaeger** [comment]
always learning: during testing the following happened: 

```
    sw360-focal: E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/universe/cnf/by-hash/SHA256/314545c8ae656be42f4cd7445add15a9986f68982416a6023c5ee6e863bce41d  
    sw360-focal: E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/universe/i18n/by-hash/SHA256/722d718d9651d94caa3092d9e952e7e5bd410ee9c43090934feae00a8e839986  File has unexpected size (13197 != 82088). Mirror sync in progress? [IP: 91.189.91.38 80]
    sw360-focal:    Hashes of expected file:
    sw360-focal:     - Filesize:82088 [weak]
    sw360-focal:     - SHA256:722d718d9651d94caa3092d9e952e7e5bd410ee9c43090934feae00a8e839986
    sw360-focal:     - SHA1:9d7e2950fcef612ec21a83fc709fc4c946087295 [weak]
    sw360-focal: 
    sw360-focal:     - MD5Sum:7ae449691ce1bdf401b1f42a4759509f [weak]
    sw360-focal:    Release file created at: Sat, 17 Apr 2021 20:07:36 +0000
    sw360-focal: E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/universe/cnf/by-hash/SHA256/722d0f569d7447650382db6d1b775bc5a36874a0ddbcff43f909ce70292b50e2  
    sw360-focal: E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/multiverse/binary-amd64/by-hash/SHA256/e6c4a69f17f42ca4ca7dd6c374cb34fca4519cd6cb5963f8860e16fc0604a866  
    sw360-focal: E: Some index files failed to download. They have been ignored, or old ones used instead.
The SSH command responded with a non-zero exit status
```

-> in fact it can apparently happen that repositories are updates ...

**Comment by mcjaeger** [comment]
there are problems with macOS 11 big sur. Some obscure errors when starting the ubuntu focal image. It was built on macOS 10.14 mojave and tested again on macOS 10.15 catalina.

**Comment by mcjaeger** [comment]
found out that on a machine twice as fast as my machine there is consistently a clean up error at the end of the maven build as described in this issue:

https://github.com/eclipse/sw360/issues/1018

Fix seems to be to increase the max mem by 50% (see latest commit)

**Comment by mcjaeger** [comment]
tested on third computer now ...

**Comment by KoukiHama** [comment]
It is not big issue, but SPDX2_time-1.9.tar.gz_1535120734-spdx.rdf.zip in first comment in this page is not good for test.
This is because,  SPDX validation tool return error.

https://tools.spdx.org/app/validate/

image

**Pull request merged**
